package Principal;

import Insumo.CargaInsumo;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;


public class MenuPrincipal extends JFrame implements ActionListener {

    private JMenuBar mb;
    private JMenu menu1;
    private JMenuItem mi1, mi2, mi3, mi4;

    public MenuPrincipal() {

        setLayout(null);
        mb = new JMenuBar();
        setJMenuBar(mb);
        menu1 = new JMenu("Insumos");
        mb.add(menu1);
        mi1 = new JMenuItem("Carga Insumo");
        mi1.addActionListener(this);
        menu1.add(mi1);
        mi2 = new JMenuItem("Consultar/Modificar Insumo");
        mi2.addActionListener(this);
        menu1.add(mi2);
        mi3 = new JMenuItem("Cargar Tipo de Insumo");
        mi3.addActionListener(this);
        menu1.add(mi3);
        mi4 = new JMenuItem("Consultar/Modificar Tipo de Insumo");
        mi4.addActionListener(this);
        menu1.add(mi4);
    }

    public void actionPerformed(ActionEvent e) {
        Container f = this.getContentPane();
        if (e.getSource() == mi1) {
            f.setBackground(new Color(255, 0, 0));
            CargaInsumo cargaInsumo = new CargaInsumo();
            cargaInsumo.setVisible(true);
            getDefaultCloseOperation();

        }
        if (e.getSource() == mi2) {
            f.setBackground(new Color(0, 255, 0));
        }
        if (e.getSource() == mi3) {
            f.setBackground(new Color(0, 0, 255));
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }
}
